/*
 * This source file was generated by the Gradle 'init' task
 */
package uts;

import uts.view.KendaraanView;

public class App {
    public static void main(String[] args) {
        KendaraanView kendaraan = new KendaraanView();
        kendaraan.render();
    }
}
